### ISSUE TITLE
not working with react 16.3.2

### ISSUE THREAD

**Issue by th3fallen** [salvoravida/react-universal-hooks#1]
I've done the following,
```import 'react-universal-hooks';
import 'babel-polyfill';
import 'whatwg-fetch';
import 'react-hot-loader/patch';
import React from 'react';
import ReactDOM from 'react-dom';
... extra code here....

ReactDOM.render(
  <Root store={ store } history={ history } />,
  document.getElementById('wheniwork-app')
);
```
but i still get https://cl.ly/41d88eae2db5/Image%202019-04-09%20at%2012.22.40%20PM.png in a child of that main.js file... am i missing something?

**Comment by salvoravida** [comment]
React Universal Hooks : just use****** everywhere. Support React >= 16.8.0
16.3.2 is not supported.
